apiVersion: 1
datasources:
  - name: gps_health
    uid: gps_health
    type: grafana-postgresql-datasource
    access: proxy
    url: localhost:5432
    user: $GF_DATASOURCE_USER
    database: gps_health
    secureJsonData:
      password: $GF_DATASOURCE_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: true
    editable: true
